### ISSUE TITLE
Speed mouseover display, if taskbar is at the top

### ISSUE THREAD

**Issue by BitWuehler** [Ashfaaq18/OpenNetMeter#11]
I use Windows 10 and I have my taskbar at the top of the screen.
If I want to see the mouseover display, it opens, but it is out of the screen, because it pops out over the mouse, not under it.

**To Reproduce**
1. Put you taskbar to the top of the screen
2. Hover over the trayicon

**Expected behavior**
Show the display under the mouse, if the taskbar is at the top of the screen. Same thing, if you use the taskbar on the left side, it should show the display on the right of the mouse.

**App and Windows Version
 - Windows Specs: Windows 10 Pro 21H1
 - OpenNetMeter Version: 0.3.1

**Comment by Ashfaaq18** [comment]
Thanks for reporting this bug @BitWuehler, i totally forgot about the different task bar layouts.

**Comment by BitWuehler** [comment]
Sure, no problem. Thank you for your fast answer and your work! @Ashfaaq18

**Comment by Ashfaaq18** [comment]
Fix available in v0.4.0 release
