### ISSUE TITLE
Pull the window larger with the mouse

### ISSUE THREAD

**Issue by BitWuehler** [Ashfaaq18/OpenNetMeter#12]
**Is your feature request related to a problem?
I love to see all programms that use nettraffic at once. The Window to see the traffic is to smal for that.

**Describe the solution you'd like**
It would be wonderfull, if you could build in the functionality to pull the windows larger with the mouse.

Could be, that you have that allready in mind. It's only a thing that I noticed very fast.

Thank you for your work! I have been looking for something like this for some time.

**Comment by Ashfaaq18** [comment]
Hey @BitWuehler , i was thinking of resizing the window only vertically. Would that be alright?

**Comment by Ashfaaq18** [comment]
![ResizeFix_GIF](https://user-images.githubusercontent.com/27722888/156181775-35e10a4a-3755-4a70-9a9d-a4130887c7b0.gif)

@BitWuehler , does this look alright?

**Comment by BitWuehler** [comment]
Looks nice. Thank you!
