### ISSUE TITLE
Minimize

### ISSUE THREAD

**Issue by merlin555** [Ashfaaq18/OpenNetMeter#14]
Hello,

How i can setting the OpenNetMeter when start it with Windows 10, start minimized.
So it is already in the background with the Windows start.

Greetings..

Merlin

**Comment by Ashfaaq18** [comment]
Hey Merlin, greetings to you too.

Currently there is no option to start the window minimized, I genuinely forgot about this requirement.
I'll add this feature by the next release.

Btw, The program is added as a task to the windows "Task Scheduler". You can manipulate the settings there for now.

**Comment by merlin555** [comment]
Hi Ashfaaq18,

Thank you for your prompt reply.
Can happen :-)
I have just looked at the Task Scheduler.
Only I do not know the command yet.

I have two ideas where you could install in your tool.

The icon below in the bar (world globe), change, so you see a bar for download and upload.
Look at: "NetMeter EVO", that apparently is no longer developed.
[http://metal-machine.de/readerror/netmeter-evo](url)

And the "NetSpeedMonitor", unfortunately, I can not download the current version:
[https://netspeedmonitor.net/download/](url)

Greetings..

 Merlin

<img width="125" alt="DL_UP" src="https://user-images.githubusercontent.com/14818838/152657253-f33e4696-7f80-49fb-b072-b0dd702f13f3.png">
