### ISSUE TITLE
Use UAC Manifest to Always Run with Admin Permissions

### ISSUE THREAD

**Issue by war59312** [Ashfaaq18/OpenNetMeter#16]
Hi,

Suggest using UAC Manifest for the exe so it always runs as admin instead of having to ask the end user to run as admin first.

See example for C/C++: https://docs.microsoft.com/en-us/cpp/build/reference/manifestuac-embeds-uac-information-in-manifest?view=msvc-170

Best,

Will

**Comment by Ashfaaq18** [comment]
Hi @war59312, thanks for the issue. I'll see if i can implement this.
for the time being though, you could

![image](https://user-images.githubusercontent.com/27722888/153349621-8263c28e-6657-4b87-9aac-ea40d657e02f.png)

tick this checkbox and always have it open in admin mode

**Comment by Ashfaaq18** [comment]
this will be available in the next v0.6.0 release
