### ISSUE TITLE
OpenNetMeter Won't launch on Windows 11

### ISSUE THREAD

**Issue by MohammedMehdiTBER** [Ashfaaq18/OpenNetMeter#20]
**Describe the bug**
OpenNetMeter Won't launch on Windows 11 Latest Dev Version.

**To Reproduce**
Click on the launcher icon
Nothing launches

**Comment by Ashfaaq18** [comment]
Have you installed the .Net 5 runtime?
Whats the OpenNetMeter version you've downloaded? try the latest 0.5.1 release (0.5.0 is broken)
Did this run fine before a new windows 11 update?

**Comment by MohammedMehdiTBER** [comment]
> Have you installed the .Net 5 runtime? Whats the OpenNetMeter version you've downloaded? try the latest 0.5.1 release (0.5.0 is broken) Did this run fine before a new windows 11 update?

Worked after reboot, but still It doesn't support taskbar.

**Comment by Ashfaaq18** [comment]
Hi @MohammedMehdiTBER, 

Microsoft actually removed the support for that taskbar display under windows 11. To add this functionality, you'll have to install a 3rd party app like StartAllBack, this brings back some features microsoft removed from the taskbar. With this you can enable the speed display feature.

and thanks for giving an update
