### ISSUE TITLE
OpenNetMeter - open via speed display

### ISSUE THREAD

**Issue by merlin555** [Ashfaaq18/OpenNetMeter#28]
Hi Ashfaaq18,

Can you please fix that if you have "only" the speed in the bar,
that you can double-click with the left mouse button so that your program opens.
So far, this is just about the globe symbol.

Thank you.

Greetings..

 Merlin

**Comment by Ashfaaq18** [comment]
Hi @merlin555,

In the v0.9.0 release, i reimplemented the taskbar speed meter as an always on top mini widget which can be placed over the taskbar. You can right click this and open the application. And for the reason why, I've explained it [here](https://github.com/Ashfaaq18/OpenNetMeter/issues/40).

**Comment by merlin555** [comment]
Hi Ashfaaq18,

Thanks for letting me know.
It's much better now.
Very well !
