### ISSUE TITLE
Implement Network Usage Statistics by Day

### ISSUE THREAD

**Issue by Python-37** [Ashfaaq18/OpenNetMeter#39]
**Is your feature request related to a problem? Please describe.**
Hello, this software is the very tool I am looking for, could you please add a tab that can show data usage in the past several days, so that I can know the usage information of every program in the past days.

**Describe the solution you'd like**
Add a tab that can show data usage history of every program, statistics by day, or maybe set a button that could select the statistical period, such as yesterday, last 3 days, last week, and last 30 days.

I'm not sure if it's clearly stated, sorry about my bad English.

**Comment by Python-37** [comment]
Nice, thanks for your great work. As a Chinese saying goes "英雄所見略同".

**Comment by Ashfaaq18** [comment]
Hi @Python-37 , just released [version 0.11.0](https://github.com/Ashfaaq18/OpenNetMeter/releases/tag/v0.11.0). You can now get your data usage up until the [last 60 days](https://github.com/Ashfaaq18/OpenNetMeter#history-tab)  and anywhere in between.
