### ISSUE TITLE
Change taskbar network speed meter implementation to support windows 10 & 11.

### ISSUE THREAD

**Issue by Ashfaaq18** [Ashfaaq18/OpenNetMeter#40]
Microsoft stopped officially supporting the [deskband feature](https://docs.microsoft.com/en-us/windows/win32/api/shobjidl/nn-shobjidl-ideskband2) as of windows 7. The feature was still included in the following operating system releases up until windows 10 and finally [removed in windows 11](https://en.wikipedia.org/wiki/List_of_features_removed_in_Windows_11). 
Due to this, the network speed meter will not officially work on windows 11.

**Describe the solution you'd like**
Instead of installing the speed meter to the taskbar as a deskband (the current implementation), implement the meter as a mini window which will always stay on top. the user can move this mini window to any position in the desktop, especially over the taskbar.

**Comment by Python-37** [comment]
May be using a mini window is a good alternative implementation, showing an always on top window, if user move it to any side of screen, then show a very simple widget instead.

**Comment by Ashfaaq18** [comment]
A small update on the mini window implementation i'm working on

![MiniWidget_demo2](https://user-images.githubusercontent.com/27722888/167834697-ebba2276-d010-4de1-ab96-f1caac912ade.gif)

this implementation still needs some refining.

**Comment by s--p** [comment]
This doesn't work nicely if you have small icons for the taskbar activated in Windows 10 and the miniwidget is not adjustable in size, so it's too big to nicely hover over the taskbar.
