### ISSUE TITLE
Feature Request: Ability to change mini widget speed format from bit/s to byte/s

### ISSUE THREAD

**Issue by kenzietama** [Ashfaaq18/OpenNetMeter#52]
The mini widget works perfectly, it would be great if the speed format can be changed to byte/s so it will display KBps and MBps instead of Kbps and Mbps. Thanks

**Comment by EncryptedFile** [comment]
I also would prefer to see Kilobytes, and Megabytes as opposed to Kilobits and Megabits.
Perhaps a radio-box option in the settings screen for users who prefer to see Kb/Mb over KB/MB?

**Comment by Ashfaaq18** [comment]
This feature is now available in the v0.12.0 release

![image](https://user-images.githubusercontent.com/27722888/178145866-fe2b1e49-556b-46a8-98ad-fa942f2ddf76.png)
