### ISSUE TITLE
Version 0.11.1 freezes after 10-15 minutes

### ISSUE THREAD

**Issue by FDT-Dirk** [Ashfaaq18/OpenNetMeter#56]
Hi,

an hour ago, or so, I updated to 0.11.1 and since then the tool already 2-3 times freezed and I had to restart it.
The widget and the tool itself freezed, (summary tab, etc.) not just one.
I now jumped back tp 0.11.0.
I use Win10.

Kind regards
Dirk

**Comment by Ashfaaq18** [comment]
Hi @FDT-Dirk , i faced the same issue today with this latest version. 

Do you know what caused it? 

> already 2-3 times freezed

And by freezing you mean the network speed is stuck and the graph is stopped yeah? were you still able to navigate the other tabs while frozen?

**Comment by FDT-Dirk** [comment]
Hi,

now even my 0.11.0 freezed. When I open the program from taskbar I can jump between all tab's, but no tab and widget are not updating.

Kind regards
Dirk

**Comment by Ashfaaq18** [comment]
Hi @FDT-Dirk , fixed the issue. its included in the new v0.11.2 version
