### ISSUE TITLE
Need Opacity / Transparency controller option for Mini Widget

### ISSUE THREAD

**Issue by fernando47924** [Ashfaaq18/OpenNetMeter#67]
If you will add **Opacity / Transparency** controller option feature for Mini Widget that would be great.
Thanks

**Comment by Ashfaaq18** [comment]
![image](https://user-images.githubusercontent.com/27722888/194702038-a8f8724d-673a-46a9-b6a7-5123669d3042.png)

is this what you are looking for? if not could you explain your request a little more?

**Comment by vishal262** [comment]
No, this not what I'm talking about
Need a option where we can increase or decrease the opacity of Mini Widget

**Comment by Ashfaaq18** [comment]
This feature will be available in the next version (after 0.12.1)
