### ISSUE TITLE
Does not support newer .Net version

### ISSUE THREAD

**Issue by Tarek-Hasan** [Ashfaaq18/OpenNetMeter#69]
**Describe the bug**
This program doesn't open with newer .net version. It says .net framework is missing.

**To Reproduce**
1. Uninstall older .net versions (except versions ships with windows)
2. install .net 7.0
3. open the program

**App and Windows Version (please complete the following information):**
 - Windows Specs: win10 22H2
 - OpenNetMeter Version: 0.12.1

**Comment by Ashfaaq18** [comment]
Hi @Tarek-Hasan , 
I do not plan on upgrading the program to .Net 7 since there is no long term support for it. I will for .Net 8.
