### ISSUE TITLE
Disk Usage - Constantly writing to my SSD

### ISSUE THREAD

**Issue by Drasow** [Ashfaaq18/OpenNetMeter#71]
I love the software but it was one big problem for me: Disk Usage - Constantly writing to my SSD

I would suggest to save in ram the data collected and writing in disk every 10 min or maybe the user can choose that in the settings or when the program closes it saves to the disk.
Because that is the only problem for me to not use this software, I don't like this always using the disk non stop.

Thank you.

**Comment by Ashfaaq18** [comment]
Sure @Drasow, ill take a look at this issue. I'll try adding a user setting to set the update frequency.

**Comment by Ashfaaq18** [comment]
The next release will have the app write every 1 min instead of 1 second
